### ISSUE TITLE
Possibly improperly synchronized deftype

### ISSUE THREAD

**Issue by bowbahdoe** [techascent/tech.ml.dataset#251] opened 2021-06-11 01:41 UTC
I might be off base here, but I think the implementation for StringTable isn't properly synchronized.

https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/v3/dataset/string_table.clj#L59

`locking` is used for write operations but not read operations, so concurrent access with writes would be unsafe

**Comment by cnuernber** [comment] 2021-06-11 02:45
This is true and actually by design.  I should document that clearly.  

That is an implicit assumption that writing and reading in parallel to the same object such as a java array, string table, or native buffer will cause inconsistent state.   

Copying data into a buffer in parallel is supported for every container as is pure parallelized read operations.   

Opetations such as inplace increment are only safe for primitive types at the moment.

I do not want to lock on read as that I believe would adversely affect perfornance potentially in a large way but, if tested and found to be untrue then we should just lock and be done with it. 

Write has to be locked as copying data into the string table is done in parallel under the covers but never read/write at same time.

**Comment by bowbahdoe** [comment] 2021-06-11 04:17
So if operations are happening in parallel, they are either all reads or all writes.

I get the use case, but i'm not sure the right words to use to describe it.

**Comment by cnuernber** [comment] 2021-06-11 12:29
Well, right now yes.  If people start shooting themselves in the foot a bunch then we can revisit.  

I am also not sure how to describe it.  What won't  work right now is a multithreaded operation that does a read/modify/write pathway.

**Comment by cnuernber** [comment] 2021-06-14 13:11
Closing this for now.  As I said, if people are shooting themselves in the foot then we can revisit.

**Closed by cnuernber** 2021-06-14 13:11 UTC
