### ISSUE TITLE
fill-range-replace changes a datatype of the column

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#263] opened 2021-08-12 11:36 UTC
```clojure
(def ds (api/dataset {:year [2022 2024 2022 2024]
                      :loc [:a :a :b :b]}))

ds
;; => _unnamed [4 2]:
;;    | :year | :loc |
;;    |------:|------|
;;    |  2022 |   :a |
;;    |  2024 |   :a |
;;    |  2022 |   :b |
;;    |  2024 |   :b |

(ds :year)
;; => #tech.v3.dataset.column<int64>[4]
;;    :year
;;    [2022, 2024, 2022, 2024]

;; grouping doesn't change the type
(-> ds
    (api/group-by [:loc])
    (api/ungroup)
    (:year))
;; => #tech.v3.dataset.column<int64>[4]
;;    :year
;;    [2022, 2024, 2022, 2024]

;; fill-range-replace changes the datatype to a float64
(-> ds
    (api/group-by [:loc])
    (api/fill-range-replace :year 1 nil nil)
    (api/ungroup)
    (:year))
;; => #tech.v3.dataset.column<float64>[6]
;;    :year
;;    [2022, 2023, 2024, 2022, 2023, 2024]
```

(TC directly calls TMD version of `fill-range-replace`)

**Comment by cnuernber** [comment] 2021-08-18 20:01
This is a legitimate issue.  I used doubles as that creates fewer codepaths but means the result has to be doubles.  The code should check if increment is an integer and if so allow the algorithm to run in integer space if the column is an integer column.

**Comment by cnuernber** [comment] 2021-11-07 14:26
@genmeblog - closing this for now.  The issue is that the only time *not* changing the datatype will work is if max-span amount is 1.  Other values will end up lerping to fractional values so I think double is the safest bet here.

**Closed by cnuernber** 2021-11-07 14:26 UTC
